### ISSUE TITLE
support string escapes

### ISSUE THREAD

**Issue by tobymao** [JelleZijlstra/sqltree#65]
print(format("select '''y' "))

>>> print(format("select '''y' "))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/toby_mao/dev/sqlglot/env/lib/python3.8/site-packages/sqltree/formatter.py", line 821, in format
    sqltree(sql, dialect), dialect=dialect, line_length=line_length, indent=indent
  File "/Users/toby_mao/dev/sqlglot/env/lib/python3.8/site-packages/sqltree/api.py", line 12, in sqltree
    return parse(tokens, dialect)
  File "/Users/toby_mao/dev/sqlglot/env/lib/python3.8/site-packages/sqltree/parser.py", line 964, in parse
    return _parse_statement(p)
  File "/Users/toby_mao/dev/sqlglot/env/lib/python3.8/site-packages/sqltree/parser.py", line 984, in _parse_statement
    _assert_done(p)
  File "/Users/toby_mao/dev/sqlglot/env/lib/python3.8/site-packages/sqltree/parser.py", line 970, in _assert_done
    raise ParseError.from_unexpected_token(remaining, expected)
sqltree.parser.ParseError: Unexpected "'y'" (expected EOF)
0: select '''y'

in sql, the escape for a quote is another quote

**Comment by JelleZijlstra** [comment]
Ah, that's what the weird NLS_NUMERIC_CHARACTERS stuff in your benchmark was about. I am focusing on MySQL for now so I'll follow https://dev.mysql.com/doc/refman/8.0/en/string-literals.html.
