### ISSUE TITLE
support cross join

### ISSUE THREAD

**Issue by tobymao** [JelleZijlstra/sqltree#66]
>>> print(format("select x cross join y "))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/toby_mao/dev/sqlglot/env/lib/python3.8/site-packages/sqltree/formatter.py", line 821, in format
    sqltree(sql, dialect), dialect=dialect, line_length=line_length, indent=indent
  File "/Users/toby_mao/dev/sqlglot/env/lib/python3.8/site-packages/sqltree/api.py", line 12, in sqltree
    return parse(tokens, dialect)
  File "/Users/toby_mao/dev/sqlglot/env/lib/python3.8/site-packages/sqltree/parser.py", line 964, in parse
    return _parse_statement(p)
  File "/Users/toby_mao/dev/sqlglot/env/lib/python3.8/site-packages/sqltree/parser.py", line 984, in _parse_statement
    _assert_done(p)
  File "/Users/toby_mao/dev/sqlglot/env/lib/python3.8/site-packages/sqltree/parser.py", line 970, in _assert_done
    raise ParseError.from_unexpected_token(remaining, expected)
sqltree.parser.ParseError: Unexpected 'CROSS' (expected EOF)
0: select x cross join y

**Comment by JelleZijlstra** [comment]
Is that legal syntax?

```
mysql> select x cross join y;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'cross join y' at line 1
```

sqltree parses `select x from a cross join b` fine.

**Comment by tobymao** [comment]
user error
